import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
import RootContainer from "./RootContainer";
import ServiceWorkerRegister from "../components/ServiceWorkerRegister";
import SalesAttributionCapture from "@/components/SalesAttributionCapture";
import ToastContainer from "@/components/ToastContainer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="manifest" href="/manifest.webmanifest" />
        <meta name="theme-color" content="#ffffff" />
      </head>
      <body className="min-h-screen flex flex-col items-center justify-start">
        <RootContainer>
          {children}
        </RootContainer>
        <ToastContainer />
        <Suspense fallback={null}>
          <SalesAttributionCapture />
        </Suspense>
        <ServiceWorkerRegister />
      </body>
    </html>
  );
}
